<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MEKKMKP" failures="1" tests="10" name="projectSelenium.LoginTest" time="37.568" errors="0" timestamp="2020-03-16T20:50:29 CET" skipped="0">
  <testcase classname="projectSelenium.LoginTest" name="start" time="7.639"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="profileWindow" time="7.007"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="loginTrial" time="1.236"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="validMailloginTrial" time="1.260"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="invalidPwdloginTrial" time="1.128"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="validMaillogin" time="1.165"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="invalidMaillogin" time="4.279">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at projectSelenium.LoginTest.invalidMaillogin(LoginTest.java:118)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- invalidMaillogin -->
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="validlogin" time="7.586"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="profileButton" time="2.203"/>
  <system-out/>
  <testcase classname="projectSelenium.LoginTest" name="logOut" time="4.065"/>
  <system-out/>
</testsuite> <!-- projectSelenium.LoginTest -->
